dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-05/run.sh | bash
notifications:
  slack:
    secure: b1PmVRM62yMFERtd1sHtKZnwI7l2Z9PcGJCEwCpFF0UUKUVEem/HoLLeqwobLzk5gY+f9BRoIcEzZ5G/VGALvjR6AcikBkqccs6dM1Wu09h4hmTUSQjJqChqDvc2ZcRlj8Va1tTt4bRhaQKPFpVVx8vuCLH4wsR3EShqf2omUXdKnJPdPE9tueojVuNSwPWycaSiTaR2Ct1rURuzDleBc0T3dpi1nA6rwLfspssNDtcncN5GnORorko7TqQmBG9vdHT2qllFE7+yLzwy4TMlEPfYqbBRv1VpsATwE0r+2ouMjaggmJKk2qU8zJ+FS6r0bP3QNarawbDdOt6x9CjZhMNIAz00AdJ1XY4gMnSI7kqFvdwAXImX30L/OZfcVeO1PqVOeDAGeNASHoPPfegB18S3h2pIj6Kgb9A8SUrCmklwXKAB4+wD02eSRnqKRc5pRW1EAQrt+LDPrMWGaI5Al0eaG0Gh1h+TdzNC6Wz37F+8rfmxSaPB94jXDVAlUl2DzQBykbEKirvIJRaUkKRmM5C5MIyakkAjVt/nv56QzdRQ31ir9DE0eUXr58GdlmpZ/BJ337ESmlG/U1ZoLsO0UiFWdKDTTQpFiSL4OTtZ7gcTzvT3gy56MF8JwloqbElOihJPHTt2L5KK6sRfUrzUIniTbO9ndTpSFi3bPFoF5R8=
