dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-05/run.sh |
  bash
install:
- sudo -H pip install ansible-lint
- wget https://github.com/wata727/tflint/releases/download/v0.7.1/tflint_darwin_amd64.zip && sudo unzip -d /usr/bin/ tflint_darwin_amd64.zip
- wget https://releases.hashicorp.com/packer/1.2.5/packer_1.2.5_linux_amd64.zip && sudo unzip -d /usr/bin/ packer_1.2.5_linux_amd64.zip
- wget https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip && sudo unzip -d /usr/bin/ terraform_0.11.7_linux_amd64.zip
- sudo chmod +x /usr/bin/tflint /usr/bin/terraform /usr/bin/packer
before_script:
- mv packer/variables.json packer/variables.json.example
script:
- find packer -name "*.json" | xargs -n packer validate -var-file=packer/variables.json.example
- for tfstage in stage prod; do pushd terraform/${tfstage} && terraform init -backend=false && tflint --var-file=terraform.tfvars.example && terraform validate -var-file=terraform.tfvars.example; popd; done
- pushd ansible && ansible-lint -x ANSIBLE0011 -v playbooks/*.yml && popd
notifications:
  slack:
    rooms:
      secure: e7GY5E8rzs/aFt8/SErP6mhHVwM9FMTL9xM/GnCQa/GHU626ethClWUweaaDvuRMjWUvu5mSkGBbgGSSaXWkfXst+b7G41y15Fs/qsWd3nkKcHI7p+01G9Psb37E9MKf1elzvdTnfeTzUaQTvJFlrrBhgd/0d7PR5fRXk778+EUCx0qxHA321vYRVljuYybZczGpsr6DmidXXUohqJkYJs2EqmmaElSOGchEaLdabNIHqy0Y8JLF/ZLlRAZtM/7M+ObRnx+aRC8hWOFE2eTfQXB2qHQhl3TWTLXKuw9AuS99QwZS7ZkUlL+hipVJruzlss5VU/kNIXjbB5maYhS7q3b8KIhOxSuy39y8IdZAk0Fie1XE9yUJ/kMPY9C3n9q2t5iuOOGVuwzMyMlXST3w3peXvAncVBpwhBsobyNgNC0Ul6eJW3hvpE+T8mcFRfmtZrhLtf94v+0vh2cPvwi+O6YCZjHvncYDnG/+w4d8XHGv6lVtGOU37ImmtAZGGfku6NpAMfljc6MFzUT3iwcjFI33ng/99fFYI4rrCklCR0HjL1fp3N3QtJnlm1ARRijeRHt2kfshxIjmsR6ykbgSOzRvVP5Qe75Dm9MVwi6RkW2zTC1MtDaD5P0elW72goPmB/b1CLjAAwfosvqQfzy9auFGTZ5dC7847cDGazhaCgg=
