---
- name: Install MongoDB
  hosts: all
  become: true
  tasks:
  - name: import apt key from ubuntu server
    apt_key:
      id: EA312927
      keyserver: keyserver.ubuntu.com

  - name: Add mongo repository
    apt_repository:
      repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
      state: present

  - name: Install package
    apt:
      name: mongodb-org
      state: present

  - name: Enable mongo service
    service:
      name: mongod
      enabled: yes
