dist: trusty
sudo: required
language: bash
before_install:
  - curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-05/run.sh | bash
notifications:
  slack:
    rooms:
      secure: Ugv12QnjU6dDTmirp2Qdm/mEYVV10kjuFRa+LLyQzUEabUch6kNCsxPBXxo3txJqof1BY82jCxZ7IPErX0h2F9raRLZXtCd81FJ+RvHT5DGBk13thVl051jK0iZtF91PlhNYhouiHvorJdV6gGda7s0dvxCGazzHvRT03whow/UANjtm/F3ACsJWnTiorGkE3irqUS+HI8a361YE5BHM7FbH6EYRBVvujbTYbplhMsuhaR1XqFHGZp4ocAvVa49xOhCi7uRdFM9bIMwZspxqIPX74Wo9jBNj33SIO4yF502ZYIckTzn7aadr7l8M6jnV836EVYn1Onbp/aCBu05nW1AH1uCnBtwBR1xAT8EBeOulelm5YIvs+Gg9j02mX9qaxev8UZ215pLeYmKowP6myJKvFdwyKPuC7HJxZcPDf2caU7xVcjo3q3G0K7HoAswUOMOIUHoyU2et4M1p5wAL4+5bETn6fVKoZmxwQeQOvrY2XyJH8s7AZlIu5x6C+UpeDr1KTWFt9wqg+vZIjKPAp0eJFq58rOE9+KbPhoWno9dh+2dqmgYJ2ogg1hgiiN+wBlvCS7PtNJr/6TNKy153kJ+mymnzLv3pfxKLEl8Gz/pbh0BCnp6+lTiw5YOHeq1q1GQFl7o9H3Bn1F4pv5xhFFBMbcykewLdGi4drJEXRzM=
