dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-05/run.sh |
  bash
notifications:
  slack:
    secure: Bpcjf10jwTsTDJwPH4fqmLAYMLCrlj6/+0pQRBHs+CTWL5zmUQhCLjPOnFt3CdaQ2B9nBtPt+zgc6zgmOH5cXK/PKtarEk7heCvoEfg0tjragdvMuUzf533OHMY9aVxi0Js4uktsNWaimL+pRl8MPWtK2y8Hi4KCwdgZIreAH1R4NiRiOuAQ4oHsn7cP9pHzqgJ2i2sPUDMs3juGi3dEgPnv1dV+gAY0febhBNTnQcgxAqitHZhMEkdZ+LXwGSDxlhItVqSUwblWFqdxwkHvTddFpCuefs0Es6oEI0B110efMBQHpLvy+2w11GWM2g2euJ3OXXz462M1N5UO9hsc/ndfeUf0zffjawT0f5hEoNqO+8dBiPnZ1nMa5CkcykwV/fgUTbB9qYJPJSsgD1loFUQRXJY8FFviJY3M7/kSV652YHxHqXgDOSywcZr1ssDB2sRG7/PHCIn997aUi0YH5BZHvh4qaZdQJfHFhRwmjs0E/AvRZT496D6EXb3BoMC0Orzdp1KdAlZVWIHIH9tO6SjhY9wojG0NygHDv8KoHvSHScyqqPEdlJIDT+cChUWDEn3CjbZeawi0UnXLf2SIE4lt6xKRR8pk/7vJE7xQUAr9b2kJpAFnJq+hMmT6xVhEtcEKkRXH3lY6IVeL/tNbgRwnfNNNs7uFrNdIOi59trE=
